### ISSUE TITLE
Can not dispatch another command inside one command handler

### ISSUE THREAD

**Issue by kramerlee** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#102]
Hi everyone,

I just follow the wiki to configure my own project. Everything is working pretty well.
I have an Application project and an Extension method of `IServiceCollection` for registering MediatR as
```csharp
services.AddMediatR(Assembly.GetExecutingAssembly());
```
And Application project is holding all Commands-Queries of all relative services.

I have got an issue that I can not inject IMediator inside a command to dispatch another command like so.

```csharp
public class CommandA : IRequest
{
    // property
}

public class CommandAHandler : IRequestHandler<CommandA, Unit>
{
    private readonly IMediator _mediator;

    CommandAHandler(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<Unit> Handle(CommandA request, CancellationToken cancellationToken)
    {
        // a few playground with db

        await _mediator.Send(new CommandB());
    }
}

public class CommandB : IRequest
{
    // property
}

public class CommandBHandler : IRequestHandler<CommandB, Unit>
{
    private readonly DbContext _context;

    CommandBHandler(DbContext context)
    {
        _context = context;
    }

    public async Task<Unit> Handle(CommandB request, CancellationToken cancellationToken)
    {
        // a few playground with db
    }
}
```

This is the exception I receive when calling a CommandA with IMediator as a dependency
```csharp
Method not found: 'System.Threading.Tasks.Task`1<!!0> MediatR.IMediator.Send(MediatR.IRequest`1<!!0>, System.Threading.CancellationToken)'.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> MediatR.IMediator.Send(MediatR.IRequest`1<!!0>, System.Threading.CancellationToken)'.
   at Application.Agents.Commands.CommandAHandler.Handle(CommandA request, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Application.Agents.Commands.CommandAHandler.Handle(CommandA request, CancellationToken cancellationToken)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c.<Handle>b__0_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
```

Environment
```
OS: Ubuntu
IDE: Jetbrains Rider
Target framework: .NET Core 3.1
```

Thank you for your attention and any help would be appreciated!!!

**Comment by kramerlee** [comment]
After looking through the app dependencies, I saw it had MediatR twice. This is caused by dependency conflict
