### ISSUE TITLE
Error when using MediatR DI NuGet library with TestServer in integration tests

### ISSUE THREAD

**Issue by kdowswell** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#11]
I am getting the error below when running an API integration test using the Microsoft.AspNetCore.TestHost TestServer object. I don't get this error when I pull down the ServiceCollectionExtensions.cs code from the library to reproduce it in a test app. I am new to all this so I hope this isn't just a stupid question. But since I cannot reproduce the issue pulling down the code, is it a problem with the nuget package? Just wanted to give you a heads up for others that might run into this issue using the nuget package.

Thank you for all the libraries and support you give to the community, Jimmy.

```
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Xunit;

namespace TestServerExample.IntegrationTests
{
    public class ApiTests
    {
        private readonly TestServer _server;
        private readonly HttpClient _client;
        public ApiTests()
        {
            // Arrange
            _server = new TestServer(new WebHostBuilder()
                .UseStartup<Startup>());
            _client = _server.CreateClient();
        }

        [Fact]
        public async Task ReturnHelloWorld()
        {
            // Act
            var response = await _client.GetAsync("api/values/1");
            response.EnsureSuccessStatusCode();

            var responseString = await response.Content.ReadAsStringAsync();

            // Assert
            Assert.Equal("value",
                responseString);
        }
    }
}

System.IO.FileLoadException
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at TestServerExample.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder)
   at TestServerExample.IntegrationTests.ApiTests..ctor() in C:\Projects\TestServerExample\TestServerExample.IntegrationTests\ApiTests.cs:line 21
```

**Comment by jbogard** [comment]
Have you tried adding a package reference to that? It's part of the MediatR package definition correctly AFAIK.

**Comment by kdowswell** [comment]
I actually don't know if this is something that has a good fix right now. It seems like there are a lot of issues with the VS 2017 tooling for ASP.NET Core projects regarding NuGet. I've seen a bunch of GitHub issues on the asp.net repos and NuGet issues like this one https://github.com/NuGet/Home/issues/4853 and this one https://github.com/Microsoft/vstest/issues/428

I created this issue b/c this was the first instance I found of this NuGet package library dependency issue. It seems that running unit tests on a ASP.NET Core project that has NuGet dependencies on projects that have different versions of the same library as dependencies is causing issues. 

The solution from issue #428 above was to do the following in the test .proj file:
```
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```
```
<!-- Solves Problem#1 (binding error) https://github.com/Microsoft/vstest/issues/428. -->
  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <!-- Solves Problem#2 (404 when executing service calls hosted in other assemblies) -->
  <!-- https://github.com/Microsoft/vstest/issues/196.-->
  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="xunit.runner.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

These workarounds are working yet for me.. But either way just wanted to share what I've found!

**Comment by jbogard** [comment]
uggggghhhhhhh
